name: roboshop
networks:
    default:
      name: roboshop

services:
  # docker run -d --name mongodb --network=roboshop mongodb:v1
  mongodb:
    image: mongodb/mongodb:v1.0
    container_name: mongodb
    

  catalogue:
    image: catalogue/catalogue:v1.0
    container_name: catalogue
    # networks:
    # - roboshop
    depends_on:
    - mongodb

  web:
    image: web/web:v1.0
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    