networks:
    default:
      external:
        name: roboshop

services:
  # docker run -d --name mongodb --network=roboshop mongodb:v1
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    # networks:
    # - roboshop
    depends_on:
    - mongodb

  web:
    image: web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    